let wordList = [ 
    'fit',
  'sum',
  'pop',
  'dry',
  'pen',
  'eye',
  'cow',
  'ant',
  'oil',
  'fax',
  'man',
  'war',
  'lie',
  'fur',
  'lid',
  'sow',
  'dip',
  'log',
  'bee',
  'joy',
  'calm',
  'truck',
  'set',
  'team',
  'petty',
  'pour',
  'exit',
  'point',
  'ton',
  'equip',
  'field',
  'cruel',
  'colon',
  'jail',
  'blind',
  'kneel',
  'layer',
  'safe',
  'van',
  'crash',
  'fool',
  'drain',
  'sit',
  'cross',
  'kit',
  'slave',
  'bless',
  'table',
  'thigh',
  'book',
  'date',
  'tract',
  'ivory',
  'miner',
  'Koran',
  'think',
  'float',
  'pier',
  'study',
  'run',
  'ranch',
  'stock',
  'eye',
  'bus',
  'false',
  'mole',
  'disk',
  'gaffe',
  'jelly',
  'lion',
'danger',
'speaker',
'notorious',
'statement',
'stroke',
'storm',
'finance',
'union',
'miner',
'claim',
'empire',
'humanity',
'huge',
'allow',
'dismiss',
'mosaic',
'fine',
'lie',
'engineer',
'jump',
'screen',
'satisfied',
'treaty',
'heavy',
'ice cream',
'shy',
'overeat',
'gloom',
'stable',
'slime',
'bottle',
'gutter',
'struggle',
'coerce',
'wave',
'tire',
'distribute',
'bitter',
'gain',
'continuous',
'authority',
'extract',
'delete',
'rank',
'fault',
'exposure',
'loan',
'virus',
'mixture',
'joystick',
'demonstration',
  'inappropriate',
  'consciousness',
  'identification',
  'infrastructure',
  'recommendation',
  'contradiction',
  'rehabilitation',
  'communication',
  'qualification',
  'representative',
  'correspondence',
  'administration',
  'investigation',
  'discrimination',
  'understanding',
  'embarrassment',
  'preoccupation',
  'confrontation',
  'characteristic',
  'strikebreaker',
  'extraterrestrial',
  'comprehensive',
  'computer',
  'virus',
  'constellation',
  'consideration',
  'environmental',
  'superintendent',
  'disappointment',
  'revolutionary',
  'supplementary',
  'short',
  'circuit',
  'responsibility',
  'concentration',
  'entertainment',
  'radiation',
  'sickness',
  'constitutional',
 'embarrassment',
  'volunteer',
  'overcharge',
  'blue',
  'jean',
  'secretion',
  'precision',
  'convulsion',
  'declaration',
  'reference',
  'radiation',
  'sickness',
  'extension',
  'productive',
  'marketing',
  'reduction',
  'circulation',
  'helicopter',
  'development',
  'correspondence',
  'knowledge',
  'admiration',
  'attention',
  'disappointment',
  'incentive',
  'presidential',
  'entitlement',
  'acceptance',
  'sensitive',
  'wisecrack',
  'constitution',
  'conventional',
  'horseshoe',
  'leadership',
  'miscarriage',
  'advertise',
  'adventure',
  'classroom',
  'publisher',
  'reinforce',
  'clearance',
  'nationalism',
  'institution',
  'emergency',
  'representative',
  'frequency',
  'sensitivity',
  'correction',
  'monstrous',
  'revolutionary',
  'circumstance',
  'incapable',
  'constellation',
  'confrontation',
  'contradiction',
  'investigation',
  'communication',
  'supplementary',
  'preoccupation',
  'embarrassment',
  'entertainment',
  'strikebreaker',
  'qualification',
  'inappropriate',
  'revolutionary',
  'consideration',
  'environmental',
  'demonstration',
  'consciousness',
  'understanding',
  'comprehensive',
  'concentration',
]

  const sentences = [ 'Yeah, I think it\'s a good environment for learning English',
  'Courage and stupidity were all he had',
  'The Guinea fowl flies through the air with all the grace of a turtle',
  'In hopes of finding out the truth, he entered the one-room library',
  'We have a lot of rain in June',
  'Italy is my favorite country; in fact, I plan to spend two weeks there next year',
  'He wasn\'t bitter that she had moved on but from the radish',
  'The door slammed on the watermelon',
  'When she didn’t like a guy who was trying to pick her up, she started using sign language',
  'Two seats were vacant',
  'They got there early, and they got really good seats',
  'Not all people who wander are lost',
  'No matter how beautiful the sunset, it saddened her knowing she was one day older',
  'It turns out you don\'t need all that stuff you insisted you did',
  'I really want to go to work, but I am too sick to drive',
  'The paintbrush was angry at the color the artist chose to use',
  'The opportunity of a lifetime passed before him as he tried to decide between a cone or a cup',
  'She folded her handkerchief neatly',
  'Chocolate covered crickets were his favorite snack',
  'He didn’t want to go to the dentist, yet he went anyway',
  'He decided to live his life by the big beats manifesto',
  'When transplanting seedlings, candied teapots will make the task easier',
  'We have never been to Asia, nor have we visited Africa',
  'There can never be too many cherries on an ice cream sundae',
  'Buried deep in the snow, he hoped his batteries were fresh in his avalanche beacon',
  'They were excited to see their first sloth',
  'I like to leave work after my eight-hour tea-break',
  'She found his complete dullness interesting',
  'Joyce enjoyed eating pancakes with ketchup',
  'I love eating toasted cheese and tuna sandwiches',
  'He was sure the Devil created red sparkly glitter',
  'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it',
  'Truth in advertising and dinosaurs with skateboards have much in common',
  'I ate a sock because people on the Internet told me to',
  'I met an interesting turtle while the song on the radio blasted away',
  'A song can make or ruin a person’s day if they let it get to them',
  'Three generations with six decades of life experience',
  'I hear that Nancy is very pretty',
  'Nothing is as cautiously cuddly as a pet porcupine',
  'The crowd yells and screams for more memes',
  'Just go ahead and press that button',
  'Three years later, the coffin was still full of Jello',
  'We have young kids who often walk into our room at night for various reasons including clowns in the closet',
  'Some bathing suits just shouldn’t be worn by some people',
  'Sometimes, all you need to do is completely make an ass of yourself and laugh it off to realise that life isn’t so bad after all',
  'I caught my squirrel rustling through my gym bag',
  'Iguanas were falling out of the trees',
  'He was so preoccupied with whether or not he could that he failed to stop to consider if he should',
  'The memory we used to share is no longer coherent',
  'It\'s much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball',
   ]


const randomWords = (type) => {
    // let difficulty = 0
    // if(level % 5 == 0) {
    //     difficulty += 2
    // }
    const words = []
    let firstLetters = ''
    wordList.sort(() => Math.random() - 0.5);

    wordList.forEach((word, i) => {
        let first = word[0];
     if(!firstLetters.includes(first))

            words.push(word)
            firstLetters += first   
           
    })
    
   
    switch(type) {
        case 'words': {
            return words
        }
        case 'boss': {
            return sentences
        }
    }
}